### ISSUE TITLE
RavenDB v4 migration

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/topcat#323]
Issues discovered:
- [x] .NET upgrade required - v4.6.1 for dotnet core 2.0
- [x] Easy options for data migration
- [x] Install Visual C++ 2015 Redistributable Package (or newer) on Windows before installing RavenDB server
- [x] Significant breaking changes - mostly fixed, apart from below
- [x] Ninject packages are out-of-date with breaking changes
- [x] GUIDs are not longer supported for IDs
- [x] Use new embeddable mode (v4.1) or new RavenDB.TestDriver for tests. See [article](https://ravendb.net/docs/article-page/4.0/csharp/start/test-driver).
- [x] New server doesn't have the custom Lucene search index [I think this bullet was just a reminder to deploy the custom analyser?]
- [x] New API for search highlighting. Released in v4.1 https://ravendb.net/docs/article-page/4.1/csharp/indexes/querying/highlighting
- [x] Upgrade all packages to recent to bring Topcat up-to-date. 
- [x] Manual testing
- [x] Make all tests pass again

**Comment by CathyJinJNCC** [comment]
As part of this can we include deployment via Jenkins to the new servers?

**Comment by felixMasonJncc** [comment]
On hold because migration of .NET frawmwork for Raven has prompted an upgrade in Ninject. The Ninject api has breaking changes.

**Comment by CathyJinJNCC** [comment]
Embedded package has a bug (see http://issues.hibernatingrhinos.com/issue/RavenDB-12037), currently using the workaround described
